cmake_minimum_required(VERSION 2.6)
	add_executable(	classTemplates CPP_Sample/CPP/classTemplates.cpp	)
	add_executable(	destructor CPP_Sample/CPP/destructor.cpp 	)
	add_executable(	functionOverloading	CPP_Sample/CPP/functionOverloading.cpp	)
	add_executable(	multipleInheritance	CPP_Sample/CPP/multipleInheritance.cpp	)
	add_executable(	operatorOverloading CPP_Sample/CPP/operatorOverloading.cpp	)
	add_executable(	simpleif_else CPP_Sample/CPP/simpleif_else.cpp	)
	add_executable(	conditionalLoop CPP_Sample/CPP/conditionalLoop.cpp	)
	add_executable(	exceptionalHandling CPP_Sample/CPP/exceptionalHandling.cpp)
	add_executable(	functionPointers CPP_Sample/CPP/functionPointers.cpp)
	add_executable(	nameSpace CPP_Sample/CPP/nameSpace.cpp	)
	add_executable(	polymorphism CPP_Sample/CPP/polymorphism.cpp	)
	add_executable(	singleInheritence CPP_Sample/CPP/singleInheritence.cpp	)
	add_executable(	constructor	CPP_Sample/CPP/constructor.cpp	)
	add_executable(	friendFunction CPP_Sample/CPP/friendFunction.cpp	)
	add_executable(	incrementOverloading CPP_Sample/CPP/incrementOverloading.cpp	)
	add_executable(	object CPP_Sample/CPP/object.cpp	)
	add_executable(	staticMember CPP_Sample/CPP/staticMember.cpp	)	
	add_executable(	constructorOverloading CPP_Sample/CPP/constructorOverloading.cpp	)
	add_executable(	functionalTemplates CPP_Sample/CPP/functionalTemplates.cpp	)
	add_executable(	inline CPP_Sample/CPP/inline.cpp	)
	add_executable(	object CPP_Sample/CPP/object.h	)
	add_executable(	vector CPP_Sample/CPP/vector.cpp	)
	add_executable(	preprocessor CPP_Sample/CPP/preprocessor.cpp	)
	add_executable(	Constructor CPP_Sample/CPP/Constructor.cpp	)
	add_executable(	enumeration CPP_Sample/CPP/enumeration.cpp	)
	add_executable(	autoTypeDeduction CPP_Sample/CPP/autoTypeDeduction.cpp	)
	add_executable(	longLongInt CPP_Sample/CPP/longLongInt.cpp	)
	add_executable(	default_delete CPP_Sample/CPP/default_delete.cpp)
	add_executable(	pointers-1 CPP_Sample/CPP/pointers-1.cpp)
	add_executable(	unrestrictedUnion CPP_Sample/CPP/unrestrictedUnion.cpp)
	add_executable(	stringLiterals CPP_Sample/CPP/stringLiterals.cpp	)
	add_executable(	constexpr.cpp CPP_Sample/CPP/constexpr.cpp	)
	add_executable(	nullPtr CPP_Sample/CPP/nullPtr.cpp	)
	add_executable(	rValue_lValue CPP_Sample/CPP/rValue_lValue.cpp	)
	add_executable(	uniformInitialization CPP_Sample/CPP/uniformInitialization.cpp	)
	add_executable(	lambda CPP_Sample/CPP/lambda.cpp	)
	add_executable(	overide_final CPP_Sample/CPP/overide_final.cpp	)
	add_executable(	std_array CPP_Sample/CPP/std_array.cpp	)
	add_executable(	deprecated CPP_Sample/CPP/deprecated.cpp	)
	add_executable(	Digit_separators CPP_Sample/CPP/Digit_separators.cpp	)
	add_executable(	functionReturnType CPP_Sample/CPP/default_delete/functionReturnType.cpp	)
	add_executable(	genericLambda CPP_Sample/CPP/genericLambda.cpp	)
	add_executable(	tuple CPP_Sample/CPP/tuple.cpp	)
	add_executable(	userDefinedLiterals CPP_Sample/CPP/userDefinedLiterals.cpp	)
	
